variables:
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake qt5-qtbase-devel qt5-linguist qt5-qtx11extras-devel qt5-qtsvg-devel qt5-qtsvg-devel gsettings-qt-devel kiran-widgets-qt5-devel kiran-log-qt5-devel'

include:
  - project: 'os/ks-devops'
    ref: main
    file: '/entrypoint/develop/cmake.yml'
