//
// Created by lxh on 2021/8/27.
//

#ifndef KIRAN_SCREENSAVER_INCLUDE_KS_SCREENSAVER_INTERFACE_H_
#define KIRAN_SCREENSAVER_INCLUDE_KS_SCREENSAVER_INTERFACE_H_

#endif  //KIRAN_SCREENSAVER_INCLUDE_KS_SCREENSAVER_INTERFACE_H_
