#ifndef  __KS_ANIMATION_DEFINE_H__
#define __KS_ANIMATION_DEFINE_H__

// ----显示解锁框系列动画相关参数----
// 屏保上滑动画时间
#define SCREENSAVER_UP_SLIP_ANIMATION_DURATION_MS 400

// 背景窗口模糊动画延时时间
#define BACKGROUND_BLUR_ANIMATION_DELAY_MS 400
// 背景窗口模糊动画时间
#define BACKGROUND_BLUR_ANIMATION_DURATION_MS 400

// 解锁框淡入动画延时时间
#define UNLOCK_DIALOG_FADE_IN_ANIMATION_DELAY_MS 300
// 解锁框挡入动画时间
#define UNLOCK_DIALOG_FADE_IN_ANIMATION_DURATION_MS 300

// ----显示屏保系列动画相关参数----
// 屏保下滑动画时间
#define SCREENSAVER_DOWN_SLIP_ANIMATION_DURATION_MS 250

// 背景窗口清晰动画延时
#define BACKGROUND_UNBLUR_ANIMATION_DELAY_MS 0
// 背景窗口清晰动画时间
#define BACKGROUND_UNBLUR_ANIMATION_DURATION_MS 0

// 解锁框动画淡出延时时间
#define UNLOCK_DIALOG_FADE_OUT_ANIMATION_DELAY_MS 0
// 解锁框动画淡出时间
#define UNLOCK_DIALOG_FADE_OUT_ANIMATION_DURATION_MS 0

// ----进入屏保----

#endif //__KS_ANIMATION_DEFINE_H__